config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'book_comments/create'
  get 'book_comments/destroy'
  devise_for :users
  root to:'homes#top'
  get 'home/about' => 'homes#about'
  resources :users do
    resource :relationships, only: [:create, :destroy, :followings, :followers]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :books,dependent: :destroy
  attachment :profile_image

  validates :name, presence: true,length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50 }

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :follower, source: :followed
  has_many :followers, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
      user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
     @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

   private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
      render:edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def edit
    @user = User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user)
    end
  end

  def index
    @user = User.new
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def destroy
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have created book successfully."
       redirect_to user_path(@user)
    else
       render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
            <%= attachment_image_tag book_comment.user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %>
            <%= book_comment.user.name %>
            <%= book_comment.comment %>

            <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book.id, book_comment.id), method: :delete, remote: true %>
            <% end %>

      <% end %>

app/views/book_comments/_number.html.erb
コメント数：<%= book.book_comments.count %>

app/views/book_comments/create.js.erb
$('#comment_area<%= @book.id %>').html("<%= j(render "book_comments/comment", book: @book) %>");
$("textarea").val('')
$('#number_numbers<%= @book.id %>').html("<%= j(render "book_comments/number", book: @book) %>");

app/views/book_comments/destroy.js.erb
$('#comment_area<%= @book.id %>').html("<%= j(render "book_comments/comment", book: @book) %>");
$('#number_numbers<%= @book.id %>').html("<%= j(render "book_comments/number", book: @book) %>");

app/views/books/edit.html.erb
   <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
    <div class="container">
    <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	<h1>Editing Book</h1>

  <%= form_with model:@book,local:true do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title,class: "form-control book_title" %>
    </div>
   <div class="form-group">
   <%= f.label :opinion %>
   <%= f.text_area :body,class: "form-control book_body" %>
  </div>
  <div class="form-group">
   <%= f.submit class: "btn btn-success" %>
  </div>
  <%= link_to "Show", book_path(@book) %>
  <%= link_to "Back", books_path %>
  <% end %>
  </div>
  </div>
  </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
        <div class="container px-5 px-sm-0">
          <div class="row">
            <div class="col-md-3">
             <h2>User info</h2>
            <%= render 'users/user',book:@book,user: current_user %>
            </div>
            <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
                </thead>
                <tbody>

                <% @books.each do |book| %>
                  <tr>
                    <td>
                    <%= link_to user_path(book.user) do %>
                     <%= attachment_image_tag book.user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %>
                    <% end %>
                    </td>
                    <td>
                    <%= link_to book_path(book) do %>
                    <%= book.title %>
                    <% end %>
                    </td>

                    <td><%= book.body %></td>

                    <td id="favorite_buttons_<%= book.id %>">
                      <%= render "favorites/favorite", book: book %>
                    </td>

                    <td>
                     <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
                    </td>

                  </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

app/views/books/show.html.erb
<%= flash[:notice] %>

  <div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
       <%= render 'users/user',book:@new_book,user: @book.user %>
    </div>


    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		  <tr>
         <td>
           <%= link_to user_path(@book.user) do %>
           <%= attachment_image_tag @book.user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %>
	         <%= @book.user.name %>
	         <% end %>
         </td>
         <td>
           <%= link_to book_path(@book) do %>
           <%= @book.title %>
           <% end %>
         </td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>

            <td id="favorite_buttons_<%= @book.id %>">
             <%= render "favorites/favorite", book: @book %>
            </td>

          <td id="number_numbers<%= @book.id %>">
           <p><%= render "book_comments/number", book: @book %></p>
          </td>

        </tr>
      </tbody></table>
　　　<div id="comment_area<%= @book.id %>">
　　　    <%= render "book_comments/comment", book: @book %>
　　　</div>

          <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
            <%= f.text_area :comment, rows:'5' %>
            <%= f.submit "送信する" %>
          <% end %>

    </div>
  </div>
  </div>

app/views/favorites/_favorite.html.erb
   <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
       ♥<%= book.favorites.count %>
      <% end %>
    </p>
      <% else %>
     <p>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
      <% end %>
     </p>
   <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<main>
    <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
</main>

app/views/homes/top.html.erb
<%= flash[:notice] %>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/relationships/_follow.html.erb
<% if users.exists? %>
  <td><%= user.name %></td>
  <td>フォロー数: <%= user.followings.count %></td>
  <td>フォロワー数: <%= user.followers.count %></td>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/followers.html.erb
<div class="col-md-8 offset-md-1">
      <h2>Followers Users</h2>
   <% if @users.count != 0 %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
       <tr>
         <td><%= attachment_image_tag user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %></td>
         <td><%= user.name %></td>
        <td>
          フォロー数: <%= user.followings.count %>
          フォロワー数: <%= user.followers.count %>
        </td>

         <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
      <% else %>
          <p>ユーザーはいません</p>
        <% end %>
    </div>

app/views/relationships/followings.html.erb
    <div class="col-md-8 offset-md-1">
      <h2>Following Users</h2>
　　 <% if @users.count != 0 %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
       <tr>

         <td><%= attachment_image_tag user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %></td>
         <td><%= user.name %></td>
          フォロー数: <%= user.followings.count %>
          フォロワー数: <%= user.followers.count %>
         <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
       <% else %>
          <p>ユーザーはいません</p>
       <% end %>
    </div>

app/views/searches/search.html.erb
<% if @range == "User" %>
  <h2>User search for"<%= @word %>"</h2>
  <% else %>
  <h2>Book search for"<%= @word %>"</h2>
<% end %>

<table class="table table-hover table-inverse">
  <% if @range == "User" %>
  <tbody>
   <tr>
    <th>image</th>
    <th>name</th>
   </tr>
  </tbody>
  <% else %>
   <tbody>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
   </tr>
   </tbody>
<% end %>

  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %>
            <% end %>
          </td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/_user.html.erb
       <table class="table">
      <tr>
      <%= attachment_image_tag user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %>
  　　<tr>
	  　<th>name</th>
	 　 <th><%= user.name %></th>
  　　</tr>
 　　  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
    </tr>
     <tr>
      <th>フォロー数</th>
      <th>
          <%= link_to user_followings_path(user) do %>
          <%= user.followings.count %>
          <% end %>
      </th>
     </tr>
     <tr>
      <th>フォロワー数</th>
      <th>
          <%= link_to user_followers_path(user) do %>
          <%= user.followers.count %></th>
          <% end %>
      </tr>
　　　<% if current_user != user %>
       <% if current_user.following?(user) %>
        <th><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></th>
       <% else %>
        <th><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></th>
       <% end %>
      <% end %>

  </table>
<div class='row'>
<%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model:book,url: books_path,local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' %>
  </div>
   <% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>

    <%= form_with model:@user,local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name,class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction,class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
      <% end %>

app/views/users/index.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/user',book:@book,user: current_user %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
       <tr>
         <td><%= attachment_image_tag user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %></td>
         <td><%= user.name %></td>
        <td>
        <% if @users.exists? %>
          フォロー数: <%= user.followings.count %>
          フォロワー数: <%= user.followers.count %>
        <% else %>
          <p>ユーザーはいません</p>
        <% end %>
        </td>
         <td>
         <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
         <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
         <% end %>
         </td>
         <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>

app/views/users/show.html.erb
<%= flash[:notice] %>
        <div class="container px-5 px-sm-0">
          <div class="row">
            <div class="col-md-3">
               <h2>User info</h2>
            <%= render 'users/user',book:@book, user:@user %>
            </div>
            <div class="col-md-8 offset-md-1">

      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
        <% @books.each do |book| %>
        <tr>
        <td>
          <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user,:profile_image, :size =>'60x60', format: 'jpeg', fallback: "japan2.jpg" %>
          <% end %>
        </td>

        <td><%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
        </td>
        <td><%= book.body %></td>

         <td>
          <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
         </td>
        </tr>
        <% end %>
  </tbody>
  </table>
    </div>
    </div>
    </div>